FIND_PATH(CppUnitLite_INCLUDE_DIR TestHarness.h /usr/include/CppUnitLite /usr/local/include/CppUnitLite)
FIND_LIBRARY(CppUnitLite_LIBRARY NAMES CppUnitLite PATH /usr/lib /usr/local/lib)
IF (CppUnitLite_INCLUDE_DIR AND CppUnitLite_LIBRARY)
 SET(CppUnitLite_FOUND TRUE)
ENDIF (CppUnitLite_INCLUDE_DIR AND CppUnitLite_LIBRARY)
IF (CppUnitLite_FOUND)
 IF (NOT CppUnitLite_FIND_QUIETLY)
 MESSAGE(STATUS "Found CppUnitLite: ${CppUnitLite_LIBRARY}")
 ENDIF (NOT CppUnitLite_FIND_QUIETLY)
ELSE (CppUnitLite_FOUND)
 IF (CppUnitLite_FIND_REQUIRED)
 MESSAGE(FATAL_ERROR "Could not find CppUnitLite library")
 ENDIF (CppUnitLite_FIND_REQUIRED)
ENDIF (CppUnitLite_FOUND)